import * as fs from 'fs';
import * as path from 'path';
import { DatabaseManager } from '../DatabaseManager.js';
import { logger } from '../../../utils/logger.js';
import type { ObservationRow, SessionSummaryRow } from '../../sqlite/types.js';

export class HandoffGenerator {
    constructor(private dbManager: DatabaseManager) { }

    public async generateHandoff(sessionDbId: number, cwd: string): Promise<void> {
        try {
            if (!cwd || !fs.existsSync(cwd)) {
                logger.warn('SESSION', 'Cannot generate HANDOFF.md: Invalid or missing cwd', { cwd });
                return;
            }

            const session = this.dbManager.getSessionById(sessionDbId);
            if (!session || !session.memory_session_id) {
                logger.debug('SESSION', 'Skipping logic: No memory session ID linked yet.');
                return;
            }

            const memorySessionId = session.memory_session_id;
            const db = this.dbManager.getSessionStore().db;

            // We manually construct our DB query to get all observations for this session
            const stmt = db.prepare(`
        SELECT * FROM observations 
        WHERE memory_session_id = ? 
        ORDER BY created_at_epoch ASC
      `);
            const observations = stmt.all(memorySessionId) as ObservationRow[];

            if (observations.length === 0) {
                logger.debug('SESSION', 'Skipping HANDOFF.md: No observations made in this session.');
                return;
            }

            const handoffPath = path.join(cwd, 'HANDOFF.md');

            logger.info('SESSION', 'Auto-generating HANDOFF.md', { path: handoffPath, observations: observations.length });

            const content = this.formatHandoffMarkdown(session.project, observations);
            fs.writeFileSync(handoffPath, content, 'utf8');

        } catch (err: any) {
            logger.error('SESSION', 'Failed to generate HANDOFF.md', err);
        }
    }

    private formatHandoffMarkdown(project: string, observations: ObservationRow[]): string {
        const lines: string[] = [];

        lines.push(`# Session Handoff: ${project}`);
        lines.push(`*Autogenerated by Claude-mem at ${new Date().toISOString()}*`);
        lines.push('');

        const filesModified = new Set<string>();
        const filesRead = new Set<string>();
        const concepts = new Set<string>();
        const narratives: string[] = [];

        for (const obs of observations) {
            if (obs.files_modified) {
                try { JSON.parse(obs.files_modified).forEach((f: string) => filesModified.add(f)); } catch (e) { logger.debug('SESSION', 'Failed to parse files_modified JSON', { observationId: obs.id }); }
            }
            if (obs.files_read) {
                try { JSON.parse(obs.files_read).forEach((f: string) => filesRead.add(f)); } catch (e) { logger.debug('SESSION', 'Failed to parse files_read JSON', { observationId: obs.id }); }
            }
            if (obs.concepts) {
                try { JSON.parse(obs.concepts).forEach((c: string) => concepts.add(c)); } catch (e) { logger.debug('SESSION', 'Failed to parse concepts JSON', { observationId: obs.id }); }
            }
            if (obs.narrative && obs.narrative.trim() && obs.type !== 'discovery') {
                narratives.push(`- **${obs.type.toUpperCase()}**: ${obs.narrative.trim()}`);
            }
        }

        lines.push('## Executive Summary');
        if (narratives.length > 0) {
            lines.push(...narratives);
        } else {
            lines.push('*(No major narrative events recorded)*');
        }
        lines.push('');

        lines.push('## Technical Details');
        lines.push('### Concepts Touched');
        if (concepts.size > 0) {
            lines.push(Array.from(concepts).map(c => `- ${c}`).join('\n'));
        } else {
            lines.push('*(None)*');
        }
        lines.push('');

        lines.push('### Files Modified');
        if (filesModified.size > 0) {
            lines.push(Array.from(filesModified).map(f => `- \`${f}\``).join('\n'));
        } else {
            lines.push('*(None)*');
        }
        lines.push('');

        lines.push('### Files Read');
        if (filesRead.size > 0) {
            lines.push(Array.from(filesRead).map(f => `- \`${f}\``).join('\n'));
        } else {
            lines.push('*(None)*');
        }
        lines.push('');

        lines.push('## Next Steps & Remaining Uncertainties');
        lines.push('*(Agent should review this handoff and prioritize pending TODOs or continuing the task logic.*)');

        return lines.join('\n');
    }
}
